version: "3.4"

services:
  app:
    image: "app:${TAG}"
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - 8501:8501
    environment:
      - DB_URL: "postgresql://postgres:postgres@db:5432/kabanchiki"
    depends_on:
      - db

  db:
    image: postgres:11.6
    command: ["-c", "fsync=${FSYNC:-off}"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432
